### ISSUE TITLE
Api additions needed for you

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_scope_description#2]
Pls post separate wishes in the main repo. One wish per post. I cannot guess what you need…

**Comment by veksha** [comment]
> Pls post separate wishes in the main repo.

CudaText repo?

> One wish per post. I cannot guess what you need…

ability to set ghost-like text after line's end, like this:
(background color can be configurable for this text only, not for the whole line.)

"Optional is not defined"

![image](https://user-images.githubusercontent.com/275333/236327014-82b19d83-ad05-4a50-879a-e710fb07dbd8.png)

maybe to do it similarly to bookmark API.

**Comment by veksha** [comment]
i see Bookmarks2 API is almost what we need, except it doesn't draw text. and background color is painted over all line.

<i>Additional internal list Bookmarks2 exists, which holds list of background bookmarks. They have lower paint priority than usual bookmarks, so background bookmark is painted only if usual bookmark not exists. Actions BOOKMARK2_* are used for Bookmarks2 list, actions have the same meaning. Background bookmarks don't have gutter icon and mouse-over tooltip. They share the single setup with usual bookmarks.</i>

maybe it can be improved?

**Comment by veksha** [comment]
can be used by LSP,
imagine something like this:


https://user-images.githubusercontent.com/275333/236345745-462eb48a-a7df-4ab6-ad4d-508a18a9bf01.mp4



```diff
diff --git a/atsynedit/atsynedit.pas b/atsynedit/atsynedit.pas
index 35d6df3f..49bdc53b 100644
--- a/atsynedit/atsynedit.pas
+++ b/atsynedit/atsynedit.pas
@@ -3717,6 +3717,7 @@ var
   bHiliteLinesWithSelection: boolean;
   bTrimmedNonSpaces: boolean;
   bUseColorOfCurrentLine: boolean;
+  NIndex: integer;
 begin
   St:= Strings;
   bHiliteLinesWithSelection:= false;
@@ -3971,6 +3972,28 @@ begin
         TextOutProps
         );
 
+      if Assigned(St.GutterDecor1) then begin
+        NIndex:= St.GutterDecor1.Find(NLinesIndex);
+        if (NIndex>=0) and (St.GutterDecor1.FindHintForLine(NLinesIndex) <> '') then begin
+          C.Brush.Color:= Colors.BlockSepLine;
+          C.FillRect(
+            CurrPointText.X+NOutputStrWidth,
+            CurrPointText.Y,
+            CurrPointText.X+NOutputStrWidth+3000,
+            CurrPointText.Y+100);
+
+          C.Font.Color:= clGray;
+          CanvasTextOut(C,
+            CurrPointText.X+NOutputStrWidth,
+            CurrPointText.Y,
+            '   //'+St.GutterDecor1.FindHintForLine(NLinesIndex),
+            nil,
+            NOutputStrWidth,
+            TextOutProps
+            );
+        end;
+      end;
+
       //paint selection bg, after applying ColorAfterEol
       DoPaintSelectedLineBG(C, ACharSize, ARectLine,
         CurrPoint,

```

**Comment by Alexey-T** [comment]
Pls, post the issue to Cud repo, I may forget to look into __this__ issue

**Comment by Alexey-T** [comment]
Maybe Decor structure can be reused here, but ok name is EndsDecor (not GutterDecor1).

**Comment by Alexey-T** [comment]
Hard part of code: adjusting decor items when user edits text, inserts/deletes lines. So I postpone it a little.

**Comment by Alexey-T** [comment]
Hard part 2: adding ImageList support for EndsDecor. Hard part 3: adding API for python and testing it.
