### ISSUE TITLE
panel mode does not work when font_scale==0

### ISSUE THREAD

**Issue by veksha** [veksha/cuda_scope_description#3]
@Alexey-T
i think you didn't see panel mode of this plugin.
because it was working only when `font_scale` was set to other then default value.

**Comment by veksha** [comment]
fixed

**Comment by veksha** [comment]
also in panel mode after caret move, caret disappears for some time.. bug of caret painting?

**Comment by Alexey-T** [comment]
I did not test the plugin yet, sorry
